Update manual-environment-greeting.yaml

diff --git a/.github/workflows/manual-environment-greeting.yaml b/.github/workflows/manual-environment-greeting.yaml
--- a/.github/workflows/manual-environment-greeting.yaml
+++ b/.github/workflows/manual-environment-greeting.yaml
@@ -4,35 +4,78 @@ on:
   workflow_dispatch:
     inputs:
       stack:
-        description: 'Select the specific stack to update (e.g., foo-prod)'
+        description: 'Select the specific stack to update (e.g., acm-prod or observability)'
         type: choice
         required: true
         options:
-          - foo-prod
-          
+          - acm-prod
+          - observability
+      environment:
+        description: 'Select the environment (e.g., dev) - required for non-suffixed stacks'
+        type: choice
+        required: false
+        options:
+          - dev
+          - staging
+          - prod
+          - default
+      action:
+        description: 'Select the action to perform (preview or update)'
+        type: choice
+        required: true
+        options:
+          - preview
+          - update
+
 env:
   AWS_DEFAULT_REGION: us-east-1
 
 jobs:
   extract-and-set-vars:
-    runs-on: ubuntu-latest
+    runs-on: [ "self-hosted", "intentsify", "dev" ]
     outputs:
       stack-prefix: ${{ steps.set-vars.outputs.stack-prefix }}
       stack-suffix: ${{ steps.set-vars.outputs.stack-suffix }}
+      apply: ${{ steps.set-vars.outputs.apply }}
     steps:
       - name: Extract stack parts and set output
         id: set-vars
         run: |
-          STACK=${{ inputs.stack }}
+          STACK=${{ github.event.inputs.stack }}
+          ENVIRONMENT=${{ github.event.inputs.environment }}
+          ACTION=${{ github.event.inputs.action }}
+          APPLY=false
+
+          if [ "$ACTION" = "update" ]; then
+            APPLY=true
+          fi
+
           IFS='-' read -r STACK_PREFIX STACK_SUFFIX <<< "$STACK"
+
+          if [ -z "$STACK_SUFFIX" ]; then
+            if [ -z "$ENVIRONMENT" ] || [ "$ENVIRONMENT" = "default" ]; then
+              echo "Environment input is required for non-suffixed stacks."
+              exit 1
+            fi
+            STACK_SUFFIX=$ENVIRONMENT
+          else
+            if [ "$ENVIRONMENT" = "default" ]; then
+              STACK_SUFFIX=$STACK_SUFFIX
+            else
+              echo "Environment input should be 'default' for suffixed stacks."
+              exit 1
+            fi
+          fi
+
           echo "::set-output name=stack-prefix::$STACK_PREFIX"
           echo "::set-output name=stack-suffix::$STACK_SUFFIX"
+          echo "::set-output name=apply::$APPLY"
 
   update-stack:
     needs: extract-and-set-vars
     uses: ./.github/workflows/_run_pulumi.yaml
     with:
       work-dir: ./.infrastructure/${{ needs.extract-and-set-vars.outputs.stack-prefix }}
-      stack: ${{ inputs.stack }}
+      stack: ${{ github.event.inputs.stack }}-${{ needs.extract-and-set-vars.outputs.stack-suffix }}
       runner-stage: ${{ needs.extract-and-set-vars.outputs.stack-suffix }}
-      apply: true
+      apply: ${{ fromJson(needs.extract-and-set-vars.outputs.apply) }}
